GET {{base_url}}/hello

###
POST {{base_url}}/entity/add
Content-Type: application/x-www-form-urlencoded

count=10

###
GET {{base_url}}/entity/all

###
GET {{base_url}}/es/entity/all

###
DELETE {{base_url}}/entity/all

###
DELETE {{base_url}}/es/entity/all

###
GET {{base_url}}/es/entity/int?intCol=12

###
GET {{base_url}}/es/entity/keyword?keyword=橘子

###
GET {{base_url}}/es/entity/text?keyword=桃子香蕉

###
GET {{base_url}}/es/entity/text?keyword=果芒