GET {{base_url}}/user/all
Authorization: token a51503ce-3091-498e-9563-29a6c41c8ac7

###
POST {{base_url}}/user

###
POST {{base_url}}/user/login
Content-Type: application/x-www-form-urlencoded

username=user-850&password=abc123456

###
GET {{base_url}}/hello
Authorization: token a51503ce-3091-498e-9563-29a6c41c8ac7

###
POST {{base_url}}/user/logout
Authorization: token a51503ce-3091-498e-9563-29a6c41c8ac7