GET {{base_url}}/user/all
Authorization: token {{token}}

###
POST {{base_url}}/user

###
POST {{base_url}}/user/login
Content-Type: application/x-www-form-urlencoded

username=user-850&password=abc123456

###
GET {{base_url}}/hello
Authorization: token {{token}}

###
POST {{base_url}}/user/logout
Authorization: token {{token}}