/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_JniTest */

#ifndef _Included_de_honoka_test_various_test_JniTest
#define _Included_de_honoka_test_various_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_JniTest
 * Method:    messageInC
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_honoka_test_various_test_JniTest_messageInC
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
