/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_JNITest */

#ifndef _Included_de_honoka_test_various_test_JNITest
#define _Included_de_honoka_test_various_test_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_JNITest
 * Method:    messageInC
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_honoka_test_various_test_JNITest_messageInC
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
