/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_honoka_test_jni_JniTest */

#ifndef _Included_de_honoka_test_jni_JniTest
#define _Included_de_honoka_test_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_honoka_test_jni_JniTest
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_honoka_test_jni_JniTest_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
