###
POST {{auth_base_url}}/user/info
Content-Type: application/json

{
  "username": "test_user1",
  "password": "abc123"
}

###
GET {{auth_base_url}}/user/info/admin
X-Token: {{x_token}}

###
POST {{auth_base_url}}/user/login
Content-Type: application/json

{
  "username": "admin"
}

> {% client.global.set('x_token', response.body['data'].token) %}

###
# 浏览器打开
# redirect_uri不可省略，其必须是SecurityConfig中所配置的oidcClient的redirectUri中的其中一个，否则报告400
GET http://localhost:8081/oauth2/authorize?response_type=code&client_id=spring-security-test-gateway&scope=all&redirect_uri=https%3A%2F%2Fwww.baidu.com
X-Token: {{x_token}}

> {%
　let resIsObject = (typeof response.body) === 'object' && response.body['data'] != null
  client.global.set('authorize_state', resIsObject ? response.body['data']['consent']['state'] : '')
%}

###
POST {{auth_base_url}}/oauth2/authorize
Content-Type: application/x-www-form-urlencoded
X-Token: {{x_token}}

client_id=spring-security-test-gateway&state={{authorize_state}}&scope=all

###
POST {{auth_base_url}}/oauth2/token
Content-Type: application/x-www-form-urlencoded
# Authorization的值为SecurityConfig中所配置的oidcClient的clientId与clientSecret（原文），用冒号拼接，然后base64编码
Authorization: Basic c3ByaW5nLXNlY3VyaXR5LXRlc3QtZ2F0ZXdheToxMjM0NTY=

grant_type=authorization_code&code
=qwJVurIi-CHQz9FYOVa9duZxjyvHs5daCgBCXdsxu8Y1c_azNakR6-ZOL2CAHFfmjd0S00it0FF0g4zYBh009xWbNKqsfS4MOOyPh8czCH1zccPnBEJrHC141xAH6Qao&redirect_uri=https%3A%2F%2Fwww.baidu.com

> {% client.global.set('oauth2_token', response.body['access_token']) %}

###
GET {{business1_base_url}}/res1
Authorization: Bearer {{oauth2_token}}