###
POST {{auth_base_url}}/user/info
Content-Type: application/json

{
  "username": "test_user1",
  "password": "abc123"
}

###
GET {{auth_base_url}}/user/info/admin
X-Token: {{x_token}}

###
POST {{auth_base_url}}/user/login
Content-Type: application/json

{
  "username": "admin"
}

> {% client.global.set('x_token', response.body['data'].token) %}

###
# 浏览器打开
# redirect_uri不可省略，其必须是SecurityConfig中所配置的client的redirectUri中的其中一个，否则报告400
GET http://localhost:8081/oauth2/authorize?response_type=code&client_id=oauth2-client1&scope=all&redirect_uri=http
    %3A%2F%2Flocalhost:8084%2Flogin%2Foauth2%2Fcode%2Foauth2-client1
X-Token: {{x_token}}

> {%
　let resIsObject = (typeof response.body) === 'object' && response.body['data'] != null
  client.global.set('authorize_state', resIsObject ? response.body['data']['consent']['state'] : '')
%}

###
GET http://localhost:8081/oauth2/authorize?response_type=code&client_id=oauth2-client1&scope=all&redirect_uri=https
    %3A%2F%2Fwww.baidu.com
X-Token: {{x_token}}

> {%
　let resIsObject = (typeof response.body) === 'object' && response.body['data'] != null
  client.global.set('authorize_state', resIsObject ? response.body['data']['consent']['state'] : '')
%}

###
# @no-redirect
POST {{auth_base_url}}/oauth2/authorize
Content-Type: application/x-www-form-urlencoded
X-Token: {{x_token}}

client_id=oauth2-client1&state={{authorize_state}}&scope=all

###
POST {{auth_base_url}}/oauth2/token
Content-Type: application/x-www-form-urlencoded
# Authorization的值为SecurityConfig中所配置的client的clientId与clientSecret（原文），用冒号拼接，然后base64编码
Authorization: Basic b2F1dGgyLWNsaWVudDE6MTIzNDU2

grant_type=authorization_code&code
=OAcWsi3Xyepq6RK5bOy-QOm0foWbnK6OB8xbeQpyJL2KEkAtdTgZDFBmoiZ_hYnALYsavJzZa5YeA7pFTdWsvRHwzFPOte0fRt3F5RzMi4_eQPwPeLotgksTRpIK0FGq&redirect_uri=http%3A%2F%2Flocalhost:8084%2Flogin%2Foauth2%2Fcode%2Foauth2-client1

> {% client.global.set('oauth2_token', response.body['access_token']) %}

###
GET {{business1_base_url}}/res1
Authorization: Bearer {{oauth2_token}}

###
GET {{business1_base_url}}/res2
Authorization: Bearer {{oauth2_token}}

###
GET {{business2_base_url}}/res1
Authorization: Bearer {{oauth2_token}}

###
GET {{auth_client1_base_url}}/test1

###
GET {{auth_client1_base_url}}/login/oauth2/code/oauth2-client1?code=SaaAJNm-8sGx_O2sjzFyfqRvB6_Os_iifGWevZsFjC7e
    -9ekMQo-DW1Lg_AtG6KvOW5T5M93W-bANJrpSRmy_iY88Ze8sTUculkE5kdc2e2LNJlAFIl9EO6-RgGIuSg0