###
POST {{auth_base_url}}/user/register
Content-Type: application/json

{
  "username": "test_user1",
  "password": "abc123"
}

###
GET {{auth_base_url}}/user/info/admin
Authorization: Bearer {{oauth2_token}}

###
POST {{auth_base_url}}/user/login
Content-Type: application/json

{
  "username": "admin"
}

> {% client.global.set('x_token', response.body['data'].token) %}

###
# 浏览器打开
# redirect_uri不可省略，其必须是SecurityConfig中所配置的client的redirectUri中的其中一个，否则报告400
GET http://localhost:8081/oauth2/authorize?response_type=code&client_id=oauth2-client1&scope=all&redirect_uri=http%3A%2F%2Flocalhost:8084%2Flogin%2Foauth2%2Fcode%2Foauth2-client1
X-Token: {{x_token}}

> {%
　let resIsObject = (typeof response.body) === 'object' && response.body['data'] != null
  client.global.set('authorize_state', resIsObject ? response.body['data']['consent']['state'] : '')
%}

###
GET http://localhost:8081/oauth2/authorize?response_type=code&client_id=oauth2-client1&scope=all&redirect_uri=https%3A%2F%2Fwww.baidu.com
X-Token: {{x_token}}

> {%
　let resIsObject = (typeof response.body) === 'object' && response.body['data'] != null
  client.global.set('authorize_state', resIsObject ? response.body['data']['consent']['state'] : '')
%}

###
POST {{auth_base_url}}/oauth2/authorize
Content-Type: application/x-www-form-urlencoded
X-Token: {{x_token}}

client_id=oauth2-client1&state={{authorize_state}}&scope=all

###
POST {{auth_base_url}}/oauth2/token
Content-Type: application/x-www-form-urlencoded
# Authorization的值为SecurityConfig中所配置的client的clientId与clientSecret（原文），用冒号拼接，然后base64编码
Authorization: Basic b2F1dGgyLWNsaWVudDE6MTIzNDU2

grant_type=authorization_code&code
=xza9UBJj2YBwEYQiGhu3LGUX7F_lQ4U41Phu6MeBfSMwWTGyPa-SIwI65eNgTSUgvaTPDJgNQFKo1P3fNlEcYxmOiy3R-hyqAOzsjZiPcjNMESoEgUqbmghlzkMxrC5j&redirect_uri=http%3A%2F%2Flocalhost:8084%2Flogin%2Foauth2%2Fcode%2Foauth2-client1

> {% client.global.set('oauth2_token', response.body['access_token']) %}

###
POST {{auth_base_url}}/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic b2F1dGgyLWNsaWVudDE6MTIzNDU2

grant_type=authorization_code&code
=Jqdy3iCilYJkN_inIJc2b8uhwnh28PQWwzNYZyiLrfSTQwY3IBklLyd249GwEN_YMkZQu2nEE9jnpCYvNVmuH2LsJevnuCQad2snuu4X2QM1gRUAsSwpvJEee3axXDev&redirect_uri=https%3A%2F%2Fwww.baidu.com

> {% client.global.set('oauth2_token', response.body['access_token']) %}

###
GET {{business1_base_url}}/res1
Authorization: Bearer {{oauth2_token}}

###
GET {{business1_base_url}}/res2
Authorization: Bearer {{oauth2_token}}

###
GET {{business2_base_url}}/res1
Authorization: Bearer {{oauth2_token}}

###
# @no-redirect
GET {{auth_client1_base_url}}/test1
Authorization: Bearer eyJraWQiOiI2YjVlZTgzMy1mNWE3LTRjYjQtOTE0Yy1mYmFmYmJiZjBiZmIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6Im9hdXRoMi1jbGllbnQxIiwibmJmIjoxNzIyNTg5NjA2LCJzY29wZSI6WyJhbGwiXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIiwiZXhwIjoxNzIyNTg5OTA2LCJpYXQiOjE3MjI1ODk2MDYsImp0aSI6IjhkOWY3ZDE0LTMxMWYtNDU3NS1iMGU4LWUzMTMzYzhjNGQ2NCJ9.thVUe2Bu35AuOBOFU9YbP1gAXJa1szBGSsyaZo94Eq46w4BU9FKP-YkLa4RRUEATeWCEfSZRYAKqgUDjEJm_0H4Ljkko1aAWRCSa-Np_zH4PzJlzGF6UOY-qAd_C9cKzPal_SWLF8fyXA1pNcbkEYsvcjiEBTTb_qG8j_9KvlCQ1JQzSHVCp34QTFwWGWtj9XxmT3t1_1ltNcPIXb5Xvy117s20HUI8ljkBeXeyuzkywmmmv4Ok-SvSYHkh2CzNq-vSK1OotbhBxLQCUsgA6i2gltdaLD5Oou9tw3PDINCz0i13QnfZMsDN5jy8zUS3zN32vXoVBuACWlh6Gh7HJ6g

###
# @no-redirect
GET {{auth_client1_base_url}}/oauth2/authorization/oauth2-client1

###
# @no-redirect
GET http://localhost:8081/oauth2/authorize?response_type=code&client_id=oauth2-client1&scope=all&state=IXEPPQXVuwCphNggJSaIXZMPUDaHA7OxU8WAEAw_l88%3D&redirect_uri=http://localhost:8084/login/oauth2/code/oauth2-client1
X-Token: {{x_token}}

###
GET http://localhost:8084/login/oauth2/code/oauth2-client1?code=4t4pOAZZTRbRQeS4_khYUF_FeQzLxpyJZaFmk0Xb2IJA9yLSm4j4vlsI_lVeCwD0upG_Ypaf_62Cy-j79SoHIDJFFdUdP_OaKr2wSDYaB6vnJh806n7aIuEvWpVuVT2S&state=IXEPPQXVuwCphNggJSaIXZMPUDaHA7OxU8WAEAw_l88%3D
